import _config_constants_ as cons
import _config_setup_ as setup

LABEL_LIMIT = int(cons.USE_RATIO * setup.LABEL_RATIO * cons.TRAIN_DATA_SIZE)
POS_COUNT_LIMIT = int(LABEL_LIMIT * cons.POS_RATIO)
NEG_COUNT_LIMIT = int(LABEL_LIMIT * cons.NEG_RATIO)
NEU_COUNT_LIMIT = int(LABEL_LIMIT * cons.NEU_RATIO)
UN_LABEL_LIMIT = int(cons.USE_RATIO * (1 - setup.LABEL_RATIO) * cons.TRAIN_DATA_SIZE)

# CONSTANT RELATED TO SELF-TRAINING

TEST_LIMIT = setup.TEST_LIMIT

DEFAULT_CLASSIFIER = setup.DEFAULT_CLASSIFIER

if DEFAULT_CLASSIFIER == cons.CLASSIFIER_SVM:
    DEFAULT_KERNEL = setup.DEFAULT_KERNEL
    DEFAULT_C_PARAMETER = setup.DEFAULT_C_PARAMETER
    DEFAULT_GAMMA_SVM = setup.DEFAULT_GAMMA_SVM
    DEFAULT_CLASS_WEIGHTS = setup.DEFAULT_CLASS_WEIGHTS
elif DEFAULT_CLASSIFIER == cons.CLASSIFIER_XGBOOST:
    DEFAULT_LEARNING_RATE = setup.DEFAULT_LEARNING_RATE
    DEFAULT_MAX_DEPTH = setup.DEFAULT_MAX_DEPTH
    DEFAULT_MIN_CHILD_WEIGHT = setup.DEFAULT_MIN_CHILD_WEIGHT
    DEFAULT_SILENT = setup.DEFAULT_SILENT
    DEFAULT_OBJECTIVE = setup.DEFAULT_OBJECTIVE
    DEFAULT_SUB_SAMPLE = setup.DEFAULT_SUB_SAMPLE
    DEFAULT_GAMMA_XBOOST = setup.DEFAULT_GAMMA_XBOOST
    DEFAULT_REGRESSION_ALPHA = setup.DEFAULT_REGRESSION_ALPHA
    DEFAULT_N_ESTIMATORS = setup.DEFAULT_N_ESTIMATORS
    DEFAULT_COLSAMPLE_BYTREE = setup.DEFAULT_COLSAMPLE_BYTREE
